[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "npm install",
  "cd backend && npm install --include=dev",
  "cd ../frontend && npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production" 