[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "npm install",
  "cd backend && npm install --include=dev",
  "cd ../frontend && npm install"
]

[phases.build]
cmds = [
  "cd backend && npm run build",
  "cd ../frontend && npm run build"
]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production" 