[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
cmds = ["chmod +x build.sh", "./build.sh"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production" 